---
- name: downloading vault-centric application
  get_url: >-
    url={{vault_app_url}}
    dest=/tmp/{{vault_app_zip}}
    owner=root
    group=root
    mode=0644

- name: making installation directory
  file: >-
    path={{vault_app_install_dir}}/{{vault_app_name}}
    state=directory
    owner=root
    group=root
    mode=0755
    
- name: unarchive vault-centric application
  unarchive: >-
    copy=no
    src=/tmp/{{vault_app_zip}}
    dest={{vault_app_install_dir}}/{{vault_app_name}}
    creates={{vault_app_install_dir}}/{{vault_app_name}}/{{vault_app}}

- name: link vault-centric application
  file: >-
    src={{vault_app_install_dir}}/{{vault_app_name}}/{{vault_app}}
    dest={{vault_app_install_dir}}/{{vault_app}}
    state=link
    force=yes

